version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - db

  sidekiq:
    image: project_app:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec sidekiq"
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:6.4.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
