#!/bin/bash


BASE_NAME=`echo $0 | awk -F/ '{print $NF}'`

if [ "$(uname)" == "Darwin" ]; then
  export US_ID=1000
  export GR_ID=1000
else
  export US_ID=$(id -u)
  export GR_ID=$(id -g)
fi

function build() {
  set -e
  read -p "Delete DB folder to start from scratch? (y/n): " DBDEL
  read -p "Create DB and migrations on startup? (y/n): " DBCREATE
  read -p "Want to run the seeds after the creation? (y/n): " DBSEED
  if [ "$DBDEL" == "y" ]
  then
    echo "Deleting db volume"
    docker-compose down -v
    echo "done."
  else
    docker-compose down
  fi
  docker-compose up -d --build --force-recreate
  if [ "$DBCREATE" == "y" ]
  then
    sleep 10
    bash $BASE_NAME create-db
  fi
  if [  "$DBSEED" == "y" ]; then
    bash $BASE_NAME seed
    bash $BASE_NAME clear-tmp
  fi
}

function start() {
  docker-compose up -d
}

function status() {
  docker-compose ps
}

function stop() {
  docker-compose down
}

function create_db() {
  docker-compose exec app rails db:create
  docker-compose exec app rails db:migrate
}

function path {
  echo "exporting path"
  export PATH=$PATH:$(pwd)
  echo "You can now use the CLI as a native command"
  exec $(which bash)
}

function clear-tmp {
  $BASE_NAME run rails tmp:cache:clear
}
function logs() {
  docker-compose logs -f --tail=50
}

function seed() {
  bash $BASE_NAME run rails db:seed
  bash $BASE_NAME reindex
}

function expose() {
  ngrok http 80
}

function console() {
  bash $BASE_NAME run rails c
}

case $1 in
  build)
    build
  ;;
  start)
    start
  ;;
  status)
    status
  ;;
  stop)
    stop
  ;;
  create-db)
    create_db
  ;;
  run)
    shift
    docker-compose exec app $@
  ;;
  restart)
    stop
    start
  ;;
  logs)
    logs
  ;;
  fix-perms)
    sudo chown -R $USER:$USER app/ db/ public/ config/ lib/
  ;;
  path)
    path
  ;;
  seed)
    seed
  ;;
  expose)
    expose
  ;;
  restart-mac)
    $BASE_NAME restart && sleep 15 && $BASE_NAME reindex
  ;;
  clear-tmp)
    clear-tmp
  ;;
  console)
    console
  ;;
  *)
    echo "
    Usage:
    $BASE_NAME path                Export cli to your shell
    $BASE_NAME build               You will need this if you want to build from scratch
    $BASE_NAME status              check containers status
    $BASE_NAME start/stop          Start the project by using docker-compose
    $BASE_NAME restart             restart
    $BASE_NAME restart-mac         restart and reindex
    $BASE_NAME console             run rails console
    $BASE_NAME clear-tmp           Clear tmp files like js and assets
    $BASE_NAME logs                Tail logs
    $BASE_NAME create-db           Run db create and migrations
    $BASE_NAME run command here    Run any command inside the container
    $BASE_NAME fix-perms           Experimental - fix code permission issues
    $BASE_NAME seed                Seed DB
    $BASE_NAME expose              expose with ngrok on port 80"
  ;;
esac
